### ISSUE TITLE
Old Hayai features requests

### ISSUE THREAD

**Issue by ascuccaro** [avuton/HayaiLauncher#3]
Are there any plans to implement/solve the feature requests and issues of the original HayaiLauncher repo?

I was mostly interested in these: [link1](https://github.com/seizonsenryaku/HayaiLauncher/issues/92), [link2](https://github.com/seizonsenryaku/HayaiLauncher/issues/91), [link3](https://github.com/seizonsenryaku/HayaiLauncher/issues/82), but of course, whatever you think has a higher priority should go first.

**Comment by avuton** [comment]
Hi! I, typically, implement things I'm interested in. I would also be happy to communicate with every single person with those who have ideas or PRs they'd like implemented.

Somewhat off topic, but, I need to put a blurb about this in the README.ml, but I have no intention of keeping a lot of feature requests open. Ideas are super cheap and everyone has a different idea of what they want, some of them would be pretty dreadful. It's nothing personal to anyone, but I would like to look at the 'issues' tab and see what actually needs completion, not a lot of noise.

 With all that said, I'm actually looking at [#82](https://github.com/seizonsenryaku/HayaiLauncher/issues/82) soon, and I'll probably look at [#91](https://github.com/seizonsenryaku/HayaiLauncher/issues/91) sooner than later. Don't consider this issue to carry either of those feature requests.

**Comment by avuton** [comment]
As far as #82 goes it'll take a little bit. I intend on adding this functionality, but even when it's hidden, it will be able to be _searched_. This will make it take a little longer to implement, but I think that's the right way.

**Comment by ascuccaro** [comment]
Thanks for the reply! And thanks for working on this app. :D

**Comment by avuton** [comment]
Hey, happy that my work is being used. I'm doing it for fun, for myself, but I'd be happy to hear others enjoying the work (and possibly contributing in the future). Closing, but feel free to continue the discussion or shoot me an email if there's anything else.
